2019-08-16 17:14:41,481;INFO;_internal.py; * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2019-08-16 17:14:44,108;INFO;main.py;Connecting to robot at 127.0.0.2:1000
2019-08-16 17:14:44,109;ERROR;main.py;Error message: local variable 'ALBroker' referenced before assignment
2019-08-16 17:14:44,110;ERROR;app.py;Exception on /api/connect [GET]
Traceback (most recent call last):
  File "/home/jslesing/projects/tic-tac-toe/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jslesing/projects/tic-tac-toe/local/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/jslesing/projects/tic-tac-toe/local/lib/python2.7/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/jslesing/projects/tic-tac-toe/local/lib/python2.7/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a UnboundLocalError.
2019-08-16 17:14:44,131;INFO;_internal.py;127.0.0.1 - - [16/Aug/2019 17:14:44] "GET /api/connect?ip=127.0.0.2&port=1000 HTTP/1.1" 500 -
